FROM drogonframework/drogon

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    libicu-dev

RUN mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
RUN mv /app/build/webbis-language-teacher /app/webbis-language-teacher

EXPOSE 8000

CMD [ "/app/webbis-language-teacher"]

