FROM drogonframework/drogon

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y \
    libicu-dev \
    libboost-locale-dev \
    libboost-system-dev \
    libboost-dev

RUN mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
RUN mv /app/build/yarki-language-teacher /app/yarki-language-teacher

EXPOSE 8000

CMD [ "/app/yarki-language-teacher"]

